### ISSUE TITLE
stake.us

### ISSUE THREAD

**Issue by felicityc** [Zennos/stake-crash-history#1]
Wondering if you could create a variant that uses stake.us' block hash so that this can be used for that. I have been having a ton of trouble getting it to work and was wondering what I was doing wrong. I think I am implementing their RNG variable wrong. For other sites it seemed very easy.

**Comment by felicityc** [comment]
000000000000000000066448f2f56069750fc40c718322766b6bdf63fdcf45b8 
is the hash they are using from 747460

**Comment by EdoanR** [comment]
It's pretty easy to change the block hash, I could add a options to change it, but not sure what the number `747460` mean. It's been a long time since I used stake 😅. Also I can't access the stake.us to test it out since I live in Brazil.

**Comment by felicityc** [comment]
Let me double check for you

> It's pretty easy to change the block hash, I could add a options to change it, but not sure what the number `747460` mean. It's been a long time since I used stake 😅. Also I can't access the stake.us to test it out since I live in Brazil.

It's the same implementation I think
https://bitcointalk.org/index.php?topic=5408287.new
747460 is the block they used for their block hash I wrote above, that's all https://sochain.com/block/BTC/000000000000000000066448f2f56069750fc40c718322766b6bdf63fdcf45b8/2

**Comment by EdoanR** [comment]
Ok, I connected to the website using a vpn, tested the block hash that you gave and seems to be working. I will add an option to change the block hash.

**Comment by EdoanR** [comment]
Added a checkbox to use the block hash of stake.us.

![image](https://github.com/EdoanR/stake-crash-history/assets/42870577/695af1e1-3395-41cb-ba03-3665c60efcc7)

**Comment by felicityc** [comment]
excellent! thank you
